swagger: '2.0'
info:
  description: RESTful API Demo
  version: 1.0.0
  title: Restful API

schemes:
  - http

#定义接口数据
paths:
  /captcha.jpg:
    get:
      tags:
        - 用户登录
      summary: 获取验证码
      produces:
        - application/octet-stream
      responses:
        '200':
          description: 获取验证码
  /login:
    post:
      tags:
        - 用户登录
      summary: 用户登录
      produces:
        - application/json
      parameters:
        - name: username
          description: 用户名
          in: query
          type: string
          required: true
        - name: password
          description: 密码
          in: query
          type: string
          required: true
        - name: captcha
          description: 验证码
          in: query
          type: string
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/user:
    get:
      tags:
        - 管理员管理
      summary: 管理员列表
      produces:
        - application/json
      parameters:
        - name: page
          description: 页码
          in: query
          type: integer
          required: true
        - name: limit
          description: 每页条数
          in: query
          type: integer
          required: true
        - name: sidx
          description: 排序字段
          in: query
          type: string
        - name: order
          description: 排序方式，如：asc、desc
          in: query
          type: string
      responses:
        '200':
          description: 返回管理员列表
          schema:
            $ref: '#/definitions/SysUserDO'

    post:
      tags:
        - 管理员管理
      summary: 添加管理员
      produces:
        - application/json
      parameters:
        - name: body
          description: 管理员对象
          in: body
          type: string
          schema:
            $ref: '#/definitions/SysUserDOSave'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'
    put:
      tags:
        - 管理员管理
      summary: 修改管理员
      produces:
        - application/json
      parameters:
        - name: body
          description: 管理员对象
          in: body
          type: string
          schema:
            $ref: '#/definitions/SysUserDOEdit'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/user/{id}:
    get:
      tags:
        - 管理员管理
      summary: 获取管理员信息
      produces:
        - application/json
      parameters:
        - name: id
          description: 用户ID
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: 返回管理员信息
          schema:
            $ref: '#/definitions/SysUserDO'

    delete:
      tags:
        - 管理员管理
      summary: 删除管理员
      produces:
        - application/json
      parameters:
        - name: id
          description: 用户ID
          in: path
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/user/save-batch:
    post:
      tags:
        - 管理员管理
      summary: 批量添加管理员
      produces:
        - application/json
      parameters:
        - name: body
          description: 管理员对象列表
          in: body
          type: string
          schema:
            type: array
            items:
              $ref: '#/definitions/SysUserDOSave'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/user/update-batch:
    post:
      tags:
        - 管理员管理
      summary: 批量更新管理员
      produces:
        - application/json
      parameters:
        - name: body
          description: 管理员对象列表
          in: body
          type: string
          schema:
            type: array
            items:
              $ref: '#/definitions/SysUserDOEdit'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/user/delete-batch:
    post:
      tags:
        - 管理员管理
      summary: 批量删除管理员
      produces:
        - application/json
      parameters:
        - name: body
          description: 管理员ID列表
          in: body
          type: string
          schema:
            type: array
            items:
              type: integer
              format: int64
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/user/info:
    get:
      tags:
        - 管理员管理
      summary: 当前管理员信息
      produces:
        - application/json
      responses:
        '200':
          description: 返回当前管理员信息
          schema:
            $ref: '#/definitions/SysUserDO'

  /sys/user/password:
    post:
      tags:
        - 管理员管理
      summary: 修改密码
      produces:
        - application/json
      parameters:
        - name: password
          description: 原密码
          in: query
          type: string
          required: true
        - name: newPassword
          description: 新密码
          in: query
          type: string
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/role:
    get:
      tags:
        - 角色管理
      summary: 角色列表
      produces:
        - application/json
      parameters:
        - name: page
          description: 页码
          in: query
          type: integer
          required: true
        - name: limit
          description: 每页条数
          in: query
          type: integer
          required: true
        - name: sidx
          description: 排序字段
          in: query
          type: string
        - name: order
          description: 排序方式，如：asc、desc
          in: query
          type: string
      responses:
        '200':
          description: 返回角色列表
          schema:
            $ref: '#/definitions/SysRoleDO'

    post:
      tags:
        - 角色管理
      summary: 添加角色
      produces:
        - application/json
      parameters:
        - name: body
          description: 角色对象
          in: body
          type: string
          schema:
            $ref: '#/definitions/SysRoleDOSave'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

    put:
      tags:
        - 角色管理
      summary: 修改角色
      produces:
        - application/json
      parameters:
        - name: body
          description: 角色对象
          in: body
          type: string
          schema:
            $ref: '#/definitions/SysRoleDOEdit'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/role/{id}:
    get:
      tags:
        - 角色管理
      summary: 获取角色信息
      produces:
        - application/json
      parameters:
        - name: id
          description: 角色ID
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: 返回角色信息
          schema:
            $ref: '#/definitions/SysRoleDO'

    delete:
      tags:
        - 角色管理
      summary: 删除角色
      produces:
        - application/json
      parameters:
        - name: id
          description: 角色ID
          in: path
          type: integer
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/role/save-batch:
    post:
      tags:
        - 角色管理
      summary: 批量添加角色
      produces:
        - application/json
      parameters:
        - name: body
          description: 角色对象列表
          in: body
          type: string
          schema:
            type: array
            items:
              $ref: '#/definitions/SysRoleDOSave'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/role/update-batch:
    post:
      tags:
        - 角色管理
      summary: 批量更新角色
      produces:
        - application/json
      parameters:
        - name: body
          description: 角色对象列表
          in: body
          type: string
          schema:
            type: array
            items:
              $ref: '#/definitions/SysRoleDOEdit'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/role/delete-batch:
    post:
      tags:
        - 角色管理
      summary: 批量删除角色
      produces:
        - application/json
      parameters:
        - name: body
          description: 管理员ID列表
          in: body
          type: string
          schema:
            type: array
            items:
              type: integer
              format: int64
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/role/select:
    get:
      tags:
        - 角色管理
      summary: 选择角色
      description: 添加、修改用户的时候，供选择的角色
      produces:
        - application/json
      responses:
        '200':
          description: 返回管理员列表
          schema:
            $ref: '#/definitions/SysRoleDO'

  /sys/menu:
    get:
      tags:
        - 菜单管理
      summary: 菜单列表
      produces:
        - application/json
      responses:
        '200':
          description: 返回菜单列表
          schema:
            $ref: '#/definitions/SysMenuDO'

    post:
      tags:
        - 菜单管理
      summary: 添加菜单
      produces:
        - application/json
      parameters:
        - name: body
          description: 菜单对象
          in: body
          type: string
          schema:
            $ref: '#/definitions/SysMenuDOSave'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

    put:
      tags:
        - 菜单管理
      summary: 修改菜单
      produces:
        - application/json
      parameters:
        - name: body
          description: 菜单对象
          in: body
          type: string
          schema:
            $ref: '#/definitions/SysMenuDOEdit'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/menu/{id}:
    get:
      tags:
        - 菜单管理
      summary: 获取菜单信息
      produces:
        - application/json
      parameters:
        - name: id
          description: 菜单ID
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: 返回菜单信息
          schema:
            $ref: '#/definitions/SysRoleDO'

    delete:
      tags:
        - 菜单管理
      summary: 删除菜单
      produces:
        - application/json
      parameters:
        - name: id
          description: 菜单ID
          in: path
          type: integer
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/menu/save-batch:
    post:
      tags:
        - 菜单管理
      summary: 批量添加菜单
      produces:
        - application/json
      parameters:
        - name: body
          description: 菜单对象列表
          in: body
          type: string
          schema:
            type: array
            items:
              $ref: '#/definitions/SysMenuDOSave'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/menu/update-batch:
    post:
      tags:
        - 菜单管理
      summary: 批量更新菜单
      produces:
        - application/json
      parameters:
        - name: body
          description: 菜单对象列表
          in: body
          type: string
          schema:
            type: array
            items:
              $ref: '#/definitions/SysMenuDOEdit'
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/menu/delete-batch:
    post:
      tags:
        - 菜单管理
      summary: 批量删除菜单
      produces:
        - application/json
      parameters:
        - name: body
          description: 菜单ID列表
          in: body
          type: string
          schema:
            type: array
            items:
              type: integer
              format: int64
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResultDO'

  /sys/menu/nav:
    get:
      tags:
        - 菜单管理
      summary: 导航菜单列表
      produces:
        - application/json
      responses:
        '200':
          description: 返回导航菜单列表
          schema:
            $ref: '#/definitions/SysMenuDO'

  /sys/menu/select:
    get:
      tags:
        - 菜单管理
      summary: 选择菜单
      description: 添加、修改菜单的时候，选择上级菜单接口
      produces:
        - application/json
      responses:
        '200':
          description: 返回菜单列表
          schema:
            $ref: '#/definitions/SysMenuDO'

#定义数据模型
definitions:
  ResultDO:
      type: object
      properties:
        code:
          description: 状态码 0：成功  非0：失败
          type: integer
          format: int32
        msg:
          description: 失败原因
          type: string
        success:
          description: true：成功  false：失败
          type: boolean
          
  SysUserDO:
    type: object
    properties:
      id:
        description: 用户ID
        type: integer
        format: int64
      username:
        description: 用户名
        type: string
      email:
        description: 邮箱
        type: string
      mobile:
        description: 手机号
        type: string
      status:
        description: 状态  0：禁用   1：正常
        type: integer
        format: int32
      roleIdList:
        description: 角色ID列表
        type: array
        items:
          type: integer
          format: int64
      createUserId:
        description: 创建者ID
        type: integer
        format: int64
      gmtCreate:
        description: 创建时间
        type: string
        format: date-time
      gmtModified:
        description: 最后修改时间
        type: string
        format: date-time

  SysUserDOSave:
      type: object
      properties:
        username:
          description: 用户名
          type: string
        password:
          description: 密码
          type: string
        email:
          description: 邮箱
          type: string
        mobile:
          description: 手机号
          type: string
        status:
          description: 状态  0：禁用   1：正常
          type: integer
          format: int32
        roleIdList:
          description: 角色ID列表
          type: array
          items:
            type: integer
            format: int32

  SysUserDOEdit:
      type: object
      properties:
        id:
          description: 用户ID
          type: integer
          format: int64
        username:
          description: 用户名
          type: string
        email:
          description: 邮箱
          type: string
        mobile:
          description: 手机号
          type: string
        status:
          description: 状态  0：禁用   1：正常
          type: integer
          format: int32
        roleIdList:
          description: 角色ID列表
          type: array
          items:
            type: integer
            format: int32

  SysRoleDO:
    type: object
    properties:
      id:
        description: 角色ID
        type: integer
        format: int64
      roleName:
        description: 角色名称
        type: string
      remark:
        description: 备注
        type: string
      menuIdList:
        description: 菜单ID列表
        type: array
        items:
          type: integer
          format: int64
      gmtCreate:
        description: 创建时间
        type: string
        format: date-time
      gmtModified:
        description: 创建时间
        type: string
        format: date-time

  SysRoleDOSave:
    type: object
    properties:
      roleName:
        description: 角色名称
        type: string
      remark:
        description: 备注
        type: string
      menuIdList:
        description: 菜单ID列表
        type: array
        items:
          type: integer
          format: int64

  SysRoleDOEdit:
    type: object
    properties:
      id:
        description: 角色ID
        type: integer
        format: int64
      roleName:
        description: 角色名称
        type: string
      remark:
        description: 备注
        type: string
      menuIdList:
        description: 菜单ID列表
        type: array
        items:
          type: integer
          format: int64

  SysMenuDO:
    type: object
    properties:
      id:
        description: 菜单ID
        type: integer
        format: int64
      name:
        description: 菜单名称
        type: string
      parentId:
        description: 父菜单ID，一级菜单为0
        type: integer
        format: int64
      parentName:
        description: 父菜单名称
        type: string
      url:
        description: 菜单URL
        type: string
      perms:
        description: 授权标识
        type: string
      type:
        description: 类型     0：目录   1：菜单   2：按钮
        type: integer
        format: int32
      icon:
        description: 菜单图标
        type: string
      orderNum:
        description: 排序
        type: integer
        format: int32
      open:
        description: 是否展开   true：展开   false：不展开
        type: boolean
        format: int32

  SysMenuDOSave:
    type: object
    properties:
      name:
        description: 菜单名称
        type: string
      parentId:
        description: 父菜单ID，一级菜单为0
        type: integer
        format: int64
      url:
        description: 菜单URL
        type: string
      perms:
        description: 授权标识
        type: string
      type:
        description: 类型     0：目录   1：菜单   2：按钮
        type: integer
        format: int32
      icon:
        description: 菜单图标
        type: string
      orderNum:
        description: 排序
        type: integer
        format: int32

  SysMenuDOEdit:
    type: object
    properties:
      id:
        description: 菜单ID
        type: integer
        format: int64
      name:
        description: 菜单名称
        type: string
      parentId:
        description: 父菜单ID，一级菜单为0
        type: integer
        format: int64
      url:
        description: 菜单URL
        type: string
      perms:
        description: 授权标识
        type: string
      type:
        description: 类型     0：目录   1：菜单   2：按钮
        type: integer
        format: int32
      icon:
        description: 菜单图标
        type: string
      orderNum:
        description: 排序
        type: integer
        format: int32
